import type { Metadata } from "next";
import { IBM_Plex_Sans_Thai, Outfit, Young_Serif } from "next/font/google";
import "./globals.css";

const ibm = IBM_Plex_Sans_Thai({
  subsets: ["thai"],
  weight: ["100", "500", "700"],
});

const youngSerif = Young_Serif({
  subsets: ["latin"],
  weight: "400",
});

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} antialiased`}>{children}</body>
    </html>
  );
}
